# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CookBook' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CookBook
  pod 'SwiftLint'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'Firebase/Storage'
  pod 'Kingfisher', '~> 6.0'
  pod 'Firebase/Auth'
  pod 'EasyRefresher'

end
